import { useEffect } from 'react'
import { Alert, Button, Checkbox, Col, Descriptions, Drawer, Form, Input, Radio, Row, Select, Space, Tag, Typography } from 'antd'
function ApprovalDrawer({approval,open,onClose,onSubmit}){
 const [form]=Form.useForm();useEffect(()=>{if(open)form.setFieldsValue({action:'通过',opinion:'申请用途明确，同意按项目范围授权使用。',authorization:'按项目授权',period:approval?.period,scope:approval?.project,download:approval?.method==='文件下载',api:approval?.method==='API 调用'})},[open,approval,form])
 if(!approval)return null
 const risks=[['申请人身份校验','通过'],['部门权限校验','通过'],['使用目的合理性',approval.risk==='使用目的描述不完整'?'不通过':'通过'],['使用期限合理性',approval.risk==='申请期限较长'?'需关注':'通过'],['安全等级匹配',approval.securityLevel==='重要数据'?'需关注':'通过'],['保密承诺','通过'],['数据最小化原则','通过'],['高频或批量访问风险',approval.risk==='API 高频调用'?'需关注':'通过']]
 const content=<><Typography.Title level={4}>{approval.productName}</Typography.Title><Descriptions bordered column={2} items={[['申请人',`${approval.applicant} · ${approval.role}`],['所属部门',approval.department],['联系方式',approval.contact],['历史申请次数','12 次'],['违规记录','无'],['申请编号',approval.id],['使用项目',approval.project],['使用目的',approval.purpose],['申请方式',approval.method],['使用期限',approval.period],['预计频率',approval.frequency],['跨部门共享',approval.crossDepartment],['产品编号',approval.productCode],['所属资产',approval.assetName],['质量评分',`${approval.qualityScore} 分`],['安全等级',approval.securityLevel],['责任部门',approval.ownerDepartment],['使用限制','仅限获批项目范围，不得向第三方转发']].map(([label,children],i)=>({key:i,label,children,span:['使用目的','使用限制'].includes(label)?2:1}))}/><Typography.Title className="workbench-section" level={5}>风险检查</Typography.Title><Row gutter={[10,10]}>{risks.map(([name,result])=><Col span={12} key={name}><div className="risk-check"><span>{name}</span><Tag color={result==='通过'?'success':result==='需关注'?'warning':'error'}>{result}</Tag></div></Col>)}</Row><Alert className="workbench-section" showIcon type={approval.risk==='无明显风险'?'success':'warning'} message={`风险提示：${approval.risk}`}/></>
 return <Drawer open={open} onClose={onClose} width="min(960px,94vw)" title="数据使用申请审批">{content}{approval.status==='待审批'?<><Typography.Title level={5}>审批处理</Typography.Title><Form form={form} layout="vertical" onFinish={onSubmit}><Form.Item name="action" label="处理方式" rules={[{required:true}]}><Radio.Group options={['通过','驳回','要求补充材料','转交']}/></Form.Item><Form.Item shouldUpdate noStyle>{({getFieldValue})=>{const action=getFieldValue('action');return <>{action==='转交'&&<Form.Item name="receiver" label="转交接收人" rules={[{required:true}]}><Select options={['安全管理员','数据责任人','部门负责人'].map(v=>({label:v,value:v}))}/></Form.Item>}<Form.Item name="opinion" label={action==='驳回'?'驳回原因':action==='要求补充材料'?'需补充内容':'审批意见'} rules={[{required:true,message:'请填写处理意见'}]}><Input.TextArea rows={3}/></Form.Item>{action==='通过'&&<><Row gutter={16}><Col span={12}><Form.Item name="authorization" label="授权方式"><Select options={['按项目授权','按部门授权','临时授权'].map(v=>({label:v,value:v}))}/></Form.Item></Col><Col span={12}><Form.Item name="period" label="授权期限"><Select options={['一个月','三个月','半年','一年'].map(v=>({label:v,value:v}))}/></Form.Item></Col></Row><Form.Item name="scope" label="可使用范围"><Input/></Form.Item><Space><Form.Item name="download" valuePropName="checked"><Checkbox>允许下载</Checkbox></Form.Item><Form.Item name="api" valuePropName="checked"><Checkbox>允许 API 调用</Checkbox></Form.Item></Space></>}</>}}</Form.Item><Space><Button onClick={onClose}>取消</Button><Button type="primary" htmlType="submit">确认处理</Button></Space></Form></>:<Alert className="workbench-section" type="info" showIcon message={`该申请已处理，当前状态：${approval.status}`} description={approval.opinion}/>}</Drawer>
}
export default ApprovalDrawer
