import { Card, Col, Descriptions, Drawer, List, Row, Statistic, Table, Tabs, Tag, Typography } from 'antd'
import { reviewRecords } from '../../../mock/productPublish'
function ProductDetailDrawer({product,open,onClose}){
 if(!product)return null
 const basic=<Descriptions bordered column={2} items={[["产品编号",product.code],["产品名称",product.name],["所属资产",product.assetName],["业务领域",product.domain],["所属地区",product.region],["数据格式",product.format],["质量评分",`${product.qualityScore} 分`],["负责人",product.owner],["产品描述",product.description]].map(([label,children],i)=>({key:i,label,children,span:label==='产品描述'?2:1}))}/>
 const permission=<Descriptions bordered column={2} items={[{key:1,label:'审批方式',children:product.permission},{key:2,label:'使用方式',children:product.accessMethods?.map(v=><Tag key={v}>{v}</Tag>)},{key:3,label:'可见范围',children:'设计院内部授权用户'},{key:4,label:'有效期',children:'长期'}]}/>
 const review=<Table rowKey="stage" pagination={false} dataSource={reviewRecords} columns={[['审核环节','stage'],['审核时间','time'],['审核人','reviewer'],['审核意见','opinion'],['结果','result']].map(([title,dataIndex])=>({title,dataIndex,render:dataIndex==='result'?(v)=><Tag color="success">{v}</Tag>:undefined}))}/>
 const operation=<><Row gutter={12}>{[['浏览量',product.views],['收藏',product.favorites],['申请',product.applications],['下载',product.downloads],['API 调用',product.apiCalls]].map(([title,value])=><Col span={Math.floor(24/5)} key={title}><Card><Statistic title={title} value={value}/></Card></Col>)}</Row><List className="detail-list" bordered dataSource={['最近访问：2026-07-15 10:26','最近更新：2026-07-14 16:30','价值等级：高价值']} renderItem={item=><List.Item>{item}</List.Item>}/></>
 return <Drawer open={open} onClose={onClose} width="min(920px,94vw)" title="数据产品详情"><Typography.Title level={4}>{product.name}</Typography.Title><Tabs items={[{key:'basic',label:'基本信息',children:basic},{key:'data',label:'数据说明',children:<Card>{product.description}<br/><br/>数据来源于：{product.assetName}</Card>},{key:'permission',label:'权限',children:permission},{key:'review',label:'审核记录',children:review},{key:'update',label:'更新记录',children:<List bordered dataSource={['V1.2 · 2026-07-14 · 更新数据与质量报告','V1.1 · 2026-07-01 · 优化产品标签','V1.0 · 2026-06-18 · 首次发布']} renderItem={item=><List.Item>{item}</List.Item>}/>},{key:'operation',label:'运营情况',children:operation}]}/></Drawer>
}
export default ProductDetailDrawer
